name = "blue-dot-world"
main = "index.ts"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "WORLD"
class_name = "World"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["World"]
